# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171006_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 6, 7, 6, 287398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 6, 7, 6, 286530, tzinfo=utc)),
        ),
    ]
