# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 10:04
from __future__ import unicode_literals

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171007_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='NO_PICTURE', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 10, 4, 31, 192100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 10, 4, 31, 191204, tzinfo=utc)),
        ),
    ]
