# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 15:28
from __future__ import unicode_literals

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20171007_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 15, 28, 48, 963598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 15, 28, 48, 962698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
