# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20171007_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='if_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
